spring.application.name=DemoProject

spring.datasource.url=postgresql://eventtracker_g3d4_user:7YGkTIMDi6lkNUNxJxcwDxWC7LSM8KJp@dpg-d3fpqq63jp1c73f1c56g-a/eventtracker_g3d4
spring.datasource.username=postgres
spring.datasource.password=231306
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
